spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/cloudnest?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username:
    password: 
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 60000
      connection-timeout: 300000
  data:
    redis:
      host: redis
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 3
          max-wait: -1ms