spring:
  application:
    name: cloudnest
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloudnest?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    # hikariCP配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 60000
      connection-timeout: 300000
  # redis
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 3
          max-wait: -1ms
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: icu.yeguo.cloudnest.controller
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
# 日志级别
logging:
  level:
    root: info
# server
server:
  port: 8080
  servlet:
    context-path: /api

app:
  time-zone: Asia/Shanghai